title: Renu Agrawal
description: M&E Analyst | Research & Development

remote_theme: mmistakes/minimal-mistakes@4.24.0

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag

navigation:
  main: main

